server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=fleet-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://fleet-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/fleet/**,/api/dispatcher/**

spring.cloud.gateway.server.webmvc.routes[1].id=driver-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://driver-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/driver/**
