spring.datasource.url=jdbc:mysql://localhost:3306/fleet_db
spring.datasource.username=root
spring.datasource.password=Lakshmi@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
